Homework-7
slo86/react-course-lessons pull request #7
Opened 2024-08-02 06:04 UTC by slo86

2024-08-02 14:23 UTC, zubkov7 requested changes

2024-08-02 14:23 UTC, zubkov7 commented on src/components/cart/CartItem.jsx
> +        <li className={styles.cartItem}>
`<li/>` лучше использовать при рендере списка, сам компонент CartItem можем существовать вне списка

2024-08-02 14:23 UTC, zubkov7 commented on src/components/header/Header.jsx
> +            <div className={styles.headerContent} onClick={() => navigate('/')}>
для таких кейсов лучше использовать навигацию по ссылке

2024-08-02 14:23 UTC, zubkov7 commented on src/components/menu/MenuItem.jsx
> +        <li className={styles.menuItem} onClick={onClick}>
тут тоже MenuItem может существовать вне списка, поэтому лучше уносить li в место рендера массива

2024-08-02 14:23 UTC, zubkov7 commented on src/redux/store.jsx
> +export const StoreProvider = ({children}) => {
обычно компоненты уносят в отдельные файлы

2024-08-02 14:23 UTC, zubkov7 commented on src/components/counter/DishCounter.jsx
> +        e.stopPropagation();
какая проблема решается с помощью stopPropagation?

2024-08-05 10:59 UTC, slo86 commented on src/components/counter/DishCounter.jsx
> +        e.stopPropagation();
На компоненте родителе тоже навешен обработчик onClick, мне нужно, что бы событие не всплывало.

2024-08-06 14:27 UTC, zubkov7 approved these changes

2024-08-09 03:02 UTC, merged